{
 "title": "Métricas APIs IndieWorld",
 "description": "Dashboard con las métricas de las 5 APIs del proyecto IndieWorld",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Tiempo de uso de CPU de API Usuarios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"indie-world-api-usuarios.vercel.app:80\"}",
     "legendFormat": "{{Tiempo CPU}}"
    }
   ]
  },
  {
   "title": "Tiempo de uso de CPU de API Juegos",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"indie-world-api-juegos.vercel.app:80\"}",
     "legendFormat": "{{Tiempo CPU}}"
    }
   ]
  },
  {
   "title": "Tiempo de uso de CPU de API Pagos",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"indie-world-api-pagos.vercel.app:80\"}",
     "legendFormat": "{{Tiempo CPU}}"
    }
   ]
  },
  {
   "title": "Tiempo de uso de CPU de API Guardado",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"indie-world-api-guardado.vercel.app:80\"}",
     "legendFormat": "{{Tiempo CPU}}"
    }
   ]
  },
  {
   "title": "Tiempo de uso de CPU de API Reviews",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"indie-world-api-reviews.vercel.app:80\"}",
     "legendFormat": "{{Tiempo CPU}}"
    }
   ]
  }
 ]
}